---
- name: restart server
  hosts: "ub-gf"
  gather_facts: False
  tasks:
    # async command: http://docs.ansible.com/ansible/playbooks_async.html
    - name: restart server
      command: /home/garfield/bin/simple-restart.sh goemt
      async: 600
      poll: 0
      
